# -*- coding: utf-8 -*-
"""main

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rzsG4-YxcCeFLBE8ylre7YBouj78dB_w
"""



# main.py
#from fastapi import FastAPI

app = FastAPI()

@app.get("/")
def read_root():
    return {"Hello": "Welcome to ECG clasification"}
